<?php
/**
 * URS Pharmacy ERP - خدمة المحاسبة
 * القيود اليومية وتحديث التكاليف
 */

// ========== تحديث متوسط التكلفة ==========
function updateAvgCost($pdo,$pid,$nq,$np,$branchId=null){$tid=getTenantId();$branchId=$branchId??getBranchId();$p=$pdo->prepare("SELECT stock_qty,cost_price FROM products WHERE id=? AND tenant_id=? AND branch_id=?");$p->execute([$pid,$tid,$branchId]);$r=$p->fetch();if(!$r)return;$oq=max(0,$r['stock_qty']);$oc=floatval($r['cost_price']);$tq=$oq+$nq;$ac=$tq>0?(($oq*$oc)+($nq*$np))/$tq:$np;$pdo->prepare("UPDATE products SET cost_price=? WHERE id=? AND tenant_id=? AND branch_id=?")->execute([round($ac,2),$pid,$tid,$branchId]);}

// ========== إنشاء/جلب حساب ==========
function getOrCreateAccount($pdo,$code,$name,$type){$tid=getTenantId();$s=$pdo->prepare("SELECT id FROM accounts WHERE code=? AND tenant_id=?");$s->execute([$code,$tid]);$id=$s->fetchColumn();if(!$id){$pdo->prepare("INSERT INTO accounts(tenant_id,code,name,name_ar,account_type,is_system) VALUES(?,?,?,?,?,1)")->execute([$tid,$code,$name,$name,$type]);$id=$pdo->lastInsertId();}return $id;}

// ========== إنشاء قيد يومي ==========
function createJournalEntry($pdo,$date,$desc,$refType,$refId,$lines,$userId=null){$tid=getTenantId();$s=$pdo->prepare("SELECT COALESCE(MAX(CAST(REPLACE(entry_number,'JE-','') AS UNSIGNED)),0)+1 FROM journal_entries WHERE tenant_id=?");$s->execute([$tid]);$en='JE-'.str_pad($s->fetchColumn(),6,'0',STR_PAD_LEFT);$td=array_sum(array_column($lines,'debit'));$tc=array_sum(array_column($lines,'credit'));$pdo->prepare("INSERT INTO journal_entries(tenant_id,entry_number,entry_date,description,reference_type,reference_id,total_debit,total_credit,is_auto,created_by) VALUES(?,?,?,?,?,?,?,?,1,?)")->execute([$tid,$en,$date,$desc,$refType,$refId,$td,$tc,$userId??($_SESSION['user_id']??null)]);$eid=$pdo->lastInsertId();$sl=$pdo->prepare("INSERT INTO journal_entry_lines(entry_id,account_id,debit,credit,description) VALUES(?,?,?,?,?)");foreach($lines as $l){$sl->execute([$eid,$l['account_id'],$l['debit'],$l['credit'],$l['description']??'']);if($l['debit']>0)$pdo->prepare("UPDATE accounts SET balance=balance+? WHERE id=? AND tenant_id=?")->execute([$l['debit'],$l['account_id'],$tid]);if($l['credit']>0)$pdo->prepare("UPDATE accounts SET balance=balance-? WHERE id=? AND tenant_id=?")->execute([$l['credit'],$l['account_id'],$tid]);}return $eid;}

// ========== قيد مشتريات ==========
function createPurchaseJournalEntry($pdo,$d){try{$ca=getOrCreateAccount($pdo,'1110',t('accounting.cashbox'),'asset');$ba=getOrCreateAccount($pdo,'1120',t('accounting.bank'),'asset');$ia=getOrCreateAccount($pdo,'1200','المخزون','asset');$sa=getOrCreateAccount($pdo,'2100',t('accounting.suppliers_acc'),'liability');$va=getOrCreateAccount($pdo,'2210','ضريبة مدخلات','asset');$nt=floatval($d['net_total']??0)-floatval($d['vat_amount']??0);$vt=floatval($d['vat_amount']??0);$gt=floatval($d['grand_total']??0);$pt=$d['payment_type']??'cash';$ls=[];$ls[]=['account_id'=>$ia,'debit'=>$nt,'credit'=>0,'description'=>'مشتريات بضاعة'];if($vt>0)$ls[]=['account_id'=>$va,'debit'=>$vt,'credit'=>0,'description'=>'ضريبة مدخلات'];if($pt==='credit')$ls[]=['account_id'=>$sa,'debit'=>0,'credit'=>$gt,'description'=>'مستحق للمورد'];elseif($pt==='transfer')$ls[]=['account_id'=>$ba,'debit'=>0,'credit'=>$gt,'description'=>'تحويل بنكي'];else $ls[]=['account_id'=>$ca,'debit'=>0,'credit'=>$gt,'description'=>'دفع نقدي'];createJournalEntry($pdo,$d['invoice_date'],'مشتريات - فاتورة '.$d['invoice_number'],'purchase_invoice',$d['id'],$ls);}catch(Exception $e){error_log("Purchase JE: ".$e->getMessage());}}

// ========== قيد مبيعات ==========
function createSaleJournalEntry($pdo,$d){try{$ca=getOrCreateAccount($pdo,'1110',t('accounting.cashbox'),'asset');$cda=getOrCreateAccount($pdo,'1130','نقاط البيع (مدى)','asset');$ba=getOrCreateAccount($pdo,'1120',t('accounting.bank'),'asset');$cua=getOrCreateAccount($pdo,'1300',t('accounting.customers_acc'),'asset');$ina=getOrCreateAccount($pdo,'1140','مستحقات التأمين','asset');$sa=getOrCreateAccount($pdo,'4100','إيرادات المبيعات','revenue');$coa=getOrCreateAccount($pdo,'5100','تكلفة البضاعة المباعة','expense');$ia=getOrCreateAccount($pdo,'1200','المخزون','asset');$vo=getOrCreateAccount($pdo,'2200','ضريبة القيمة المضافة المستحقة','liability');$gt=floatval($d['grand_total']??0);$vt=floatval($d['vat_amount']??0);$tc=floatval($d['total_cost']??0);$pt=$d['payment_type']??'cash';$sr=$gt-$vt;$am=['cash'=>$ca,'card'=>$cda,'network'=>$cda,'transfer'=>$ba,'credit'=>$cua,'insurance'=>$ina];$da=$am[$pt]??$ca;$ls=[];$ls[]=['account_id'=>$da,'debit'=>$gt,'credit'=>0,'description'=>'إيراد مبيعات'];$ls[]=['account_id'=>$sa,'debit'=>0,'credit'=>$sr,'description'=>'مبيعات'];if($vt>0)$ls[]=['account_id'=>$vo,'debit'=>0,'credit'=>$vt,'description'=>'ضريبة مخرجات'];if($tc>0){$ls[]=['account_id'=>$coa,'debit'=>$tc,'credit'=>0,'description'=>'تكلفة بضاعة مباعة'];$ls[]=['account_id'=>$ia,'debit'=>0,'credit'=>$tc,'description'=>'إنقاص مخزون'];}createJournalEntry($pdo,$d['invoice_date']??date('Y-m-d'),'مبيعات - فاتورة '.$d['invoice_number'],'sale_invoice',$d['id'],$ls);}catch(Exception $e){error_log("Sale JE: ".$e->getMessage());}}

// ========== قيد سند قبض ==========
function createReceiptJournalEntry($pdo,$d){try{$m=$d['payment_method']??'cash';$da=getOrCreateAccount($pdo,$m==='transfer'?'1120':'1110',$m==='transfer'?t('accounting.bank'):t('accounting.cashbox'),'asset');$cr=$d['party_type']==='customer'?getOrCreateAccount($pdo,'1300',t('accounting.customers_acc'),'asset'):getOrCreateAccount($pdo,'4200',t('accounting.other_revenue'),'revenue');createJournalEntry($pdo,$d['voucher_date'],t('receipts.receipt_voucher') . ' '.$d['voucher_number'],'receipt_voucher',$d['id'],[['account_id'=>$da,'debit'=>$d['amount'],'credit'=>0,'description'=>t('receipts.receipt_voucher')],['account_id'=>$cr,'debit'=>0,'credit'=>$d['amount'],'description'=>$d['description']??'']]);}catch(Exception $e){error_log("Receipt JE: ".$e->getMessage());}}

// ========== قيد سند صرف ==========
function createPaymentJournalEntry($pdo,$d){try{$m=$d['payment_method']??'cash';$cr=getOrCreateAccount($pdo,$m==='transfer'?'1120':'1110',$m==='transfer'?t('accounting.bank'):t('accounting.cashbox'),'asset');$da=$d['party_type']==='supplier'?getOrCreateAccount($pdo,'2100',t('accounting.suppliers_acc'),'liability'):getOrCreateAccount($pdo,'5900',t('accounting.other_expenses'),'expense');createJournalEntry($pdo,$d['voucher_date'],t('payments.payment_voucher') . ' '.$d['voucher_number'],'payment_voucher',$d['id'],[['account_id'=>$da,'debit'=>$d['amount'],'credit'=>0,'description'=>$d['description']??''],['account_id'=>$cr,'debit'=>0,'credit'=>$d['amount'],'description'=>t('payments.payment_voucher')]]);}catch(Exception $e){error_log("Payment JE: ".$e->getMessage());}}

// ========== قيد مصروفات ==========
function createExpenseJournalEntry($pdo,$d){try{$m=$d['payment_method']??'cash';$cr=getOrCreateAccount($pdo,$m==='transfer'?'1120':'1110',$m==='transfer'?t('accounting.bank'):t('accounting.cashbox'),'asset');$cm=['رواتب وأجور'=>'5200','إيجار'=>'5300','كهرباء وماء'=>'5400','صيانة'=>'5410','نقل ومواصلات'=>'5420','مستلزمات مكتبية'=>'5500','تسويق وإعلان'=>'5600','ضيافة'=>'5610','اتصالات وإنترنت'=>'5430','تأمينات'=>'5440','رسوم حكومية'=>'5450','أدوية تالفة'=>'5700','نظافة'=>'5460','أخرى'=>'5900'];$co=$cm[$d['category']]??'5900';$da=getOrCreateAccount($pdo,$co,$d['category']??t('accounting.other_expenses'),'expense');$ls=[['account_id'=>$da,'debit'=>$d['total'],'credit'=>0,'description'=>$d['description']??''],['account_id'=>$cr,'debit'=>0,'credit'=>$d['total'],'description'=>'مصروف']];if(floatval($d['vat_amount']??0)>0){$va=getOrCreateAccount($pdo,'2210','ضريبة مدخلات','asset');$ls[0]['debit']-=$d['vat_amount'];$ls[]=['account_id'=>$va,'debit'=>$d['vat_amount'],'credit'=>0,'description'=>'ضريبة مدخلات'];}createJournalEntry($pdo,$d['expense_date'],'مصروف - '.($d['category']??''),'expense',$d['id'],$ls);}catch(Exception $e){error_log("Expense JE: ".$e->getMessage());}}

// ========== قيد مرتجع مبيعات ==========
function createSalesReturnJournalEntry($pdo,$d){try{$ca=getOrCreateAccount($pdo,'1110',t('accounting.cashbox'),'asset');$cda=getOrCreateAccount($pdo,'1130','نقاط البيع (مدى)','asset');$cua=getOrCreateAccount($pdo,'1300',t('accounting.customers_acc'),'asset');$ra=getOrCreateAccount($pdo,'4110','مردودات المبيعات','revenue');$coa=getOrCreateAccount($pdo,'5100','تكلفة البضاعة المباعة','expense');$ia=getOrCreateAccount($pdo,'1200','المخزون','asset');$vo=getOrCreateAccount($pdo,'2200','ضريبة القيمة المضافة المستحقة','liability');$tr=floatval($d['total_amount']??0);$vt=floatval($d['vat_amount']??0);$tc=floatval($d['total_cost']??0);$rf=$d['refund_method']??'cash';$rr=$tr-$vt;$cm=['cash'=>$ca,'card'=>$cda,'credit'=>$cua];$cr=$cm[$rf]??$ca;$ls=[];$ls[]=['account_id'=>$ra,'debit'=>$rr,'credit'=>0,'description'=>'مردودات مبيعات'];if($vt>0)$ls[]=['account_id'=>$vo,'debit'=>$vt,'credit'=>0,'description'=>'عكس ضريبة مخرجات'];$ls[]=['account_id'=>$cr,'debit'=>0,'credit'=>$tr,'description'=>'رد مبلغ'];if($tc>0){$ls[]=['account_id'=>$ia,'debit'=>$tc,'credit'=>0,'description'=>'إعادة مخزون'];$ls[]=['account_id'=>$coa,'debit'=>0,'credit'=>$tc,'description'=>'عكس تكلفة'];}createJournalEntry($pdo,$d['return_date']??date('Y-m-d'),'مرتجع مبيعات - '.($d['return_number']??''),'sales_return',$d['id']??0,$ls);}catch(Exception $e){error_log("Sales Return JE: ".$e->getMessage());}}

// ========== قيد مرتجع مشتريات ==========
function createPurchaseReturnJournalEntry($pdo,$d){try{$ca=getOrCreateAccount($pdo,'1110',t('accounting.cashbox'),'asset');$ba=getOrCreateAccount($pdo,'1120',t('accounting.bank'),'asset');$sa=getOrCreateAccount($pdo,'2100',t('accounting.suppliers_acc'),'liability');$ia=getOrCreateAccount($pdo,'1200','المخزون','asset');$va=getOrCreateAccount($pdo,'2210','ضريبة مدخلات','asset');$t=floatval($d['total_amount']??0);$v=floatval($d['vat_amount']??0);$n=$t-$v;$pt=$d['original_payment_type']??'cash';$dm=['credit'=>$sa,'transfer'=>$ba];$da=$dm[$pt]??$ca;$ls=[];$ls[]=['account_id'=>$da,'debit'=>$t,'credit'=>0,'description'=>'استرداد مرتجع'];$ls[]=['account_id'=>$ia,'debit'=>0,'credit'=>$n,'description'=>'إنقاص مخزون'];if($v>0)$ls[]=['account_id'=>$va,'debit'=>0,'credit'=>$v,'description'=>'عكس ضريبة'];createJournalEntry($pdo,$d['return_date']??date('Y-m-d'),'مرتجع مشتريات - '.($d['return_number']??''),'purchase_return',$d['id']??0,$ls);}catch(Exception $e){error_log("PR JE: ".$e->getMessage());}}
